### ISSUE TITLE
Build: Does not work with Apache Maven 3.1

### ISSUE THREAD

**Issue by tjuerge** [sculptor/sculptor#41]
Apache Maven 3.1 has just been released which makes a change from using Sonatype Aether to using Eclipse Aether, which incurs package renames, and a few API changes.

This leads to exceptions e.g. in Tycho:

```
Exception in thread "main" java.lang.NoSuchMethodError: org.apache.maven.execution.MavenSession.getRepositorySession()Lorg/sonatype/aether/RepositorySystemSession;
    at org.eclipse.tycho.core.maven.utils.PluginRealmHelper.execute(PluginRealmHelper.java:92)
    at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.getDependencyMetadata(P2TargetPlatformResolver.java:144)
    at org.eclipse.tycho.p2.resolver.P2TargetPlatformResolver.setupProjects(P2TargetPlatformResolver.java:126)
    at org.eclipse.tycho.core.resolver.DefaultTychoDependencyResolver.setupProject(DefaultTychoDependencyResolver.java:87)
    at org.eclipse.tycho.core.maven.TychoMavenLifecycleParticipant.afterProjectsRead(TychoMavenLifecycleParticipant.java:77)
    at org.apache.maven.DefaultMaven.doExecute(DefaultMaven.java:272)
```
